### ISSUE TITLE
Create account/login system for regular users of the site

### ISSUE THREAD

**Issue by StengoS** [CSC308-TeamA/ClubTracker#12]
Time-Tracking:
4 hours estimated
4 hour taken (sprint 2)

Closed issue, going to re-make for start of CSC309

Note:
Originally went for a Firebase implementation, but forgot for the team project we should make our own custom implementation for login system

**Comment by jenisa10** [comment]
Can't use firebase....need some other form of authentication...

**Comment by jenisa10** [comment]
Note that frontend pages are ready, just needs the verification and backend implementation.
