### ISSUE TITLE
SPIKE: Research User Authentication Technology

### ISSUE THREAD

**Issue by tammychau99** [CSC308-TeamA/ClubTracker#29]
Time Estimate: 2 hours
Time Taken (Sprint 4): 3 hours

TASKS: 
- Research MongoDB User Management (https://docs.mongodb.com/manual/core/security-users/)
- Research MongoDB Role Management (https://docs.mongodb.com/manual/reference/built-in-roles/)
- Research Password hashing + management

**Comment by Jerbilcraft** [comment]
I've already done this and can talk about it during the meeting if you want my information
