### ISSUE TITLE
Add Delete Path/Method to team roster

### ISSUE THREAD

**Issue by Jerbilcraft** [CSC308-TeamA/ClubTracker#37]
Time Estimate: 2 hours
Time Taken (Sprint 5):
Time Taken (Sprint 4): 2.5 hours

must have a button in front end, a action in backend and a connection in the database.
I recommend using the mongodb _id field to identify the members in the roster on the front end

**Comment by Jerbilcraft** [comment]
Time Estimate: 2 hours
Time Taken (Sprint 4): 1 hours 
(already added to main comment - steven)

**Comment by Jerbilcraft** [comment]
Needs testing from RosterConnectFrontBack

**Comment by tammychau99** [comment]
Testing: 0.5 hour
(already added to main comment - steven)

Errors popping up with delete. 
Methods not recognized and crashes site. 
Moving back to in progress to fix methods.

**Comment by tammychau99** [comment]
working on debugging feature
