### ISSUE TITLE
(Signup Feature) Implement "Add User" functionality (back <--> db)

### ISSUE THREAD

**Issue by tammychau99** [CSC308-TeamA/ClubTracker#39]
Time estimate: 2 hours
Time taken (sprint 4): 1 hour

**TO-DO**
Function to add user accounts to the db
1. Get users from the collection to check if the email associated with the account is already created
2. if account not created yet: create account --> add user to collection
3. if account already created: don't create account, print message on frontend for user that account already exists

**Comment by jenisa10** [comment]
Finished! Did it with Node.js and MongoDB. 3 hours taken.
