### ISSUE TITLE
Convert JWT in backend to Python (PyJWT)

### ISSUE THREAD

**Issue by StengoS** [CSC308-TeamA/ClubTracker#43]
Time Estimate: 6 hours
Time Taken (Sprint 7): 3 hours
Time Taken (Sprint 5): 3 hours

**Comment by jenisa10** [comment]
3 hours so far...not yet completed.

**Comment by jenisa10** [comment]
+3 hours

**Comment by StengoS** [comment]
Closing issue since no longer making a "full" conversion/changing approach and scope to user authentication feature
