### ISSUE TITLE
Lint JS and Python code

### ISSUE THREAD

**Issue by tammychau99** [CSC308-TeamA/ClubTracker#44]
Total Time Estimate: 3 hours
Time Taken (Sprint 5): .5 hours 

Time Estimate (Sprint 6): 2 hours
Time taken (Sprint 6): 2 hour

Python code linted 9.56/10

JS code linted: All clean
Originally: 23003 problems (22452 errors, 551 warnings)

**Comment by tammychau99** [comment]
Note: Added new rule to .eslintrc.json to allow .js file extensions

**Comment by tammychau99** [comment]
**New rules**

Rules Added: 
    "rules": {
        "react/jsx-filename-extension": [1, { "extensions": [".js", ".jsx"] }],
        "max-len": [1, { "ignoreStrings": true, "ignoreUrls": true }],
        "indent": [2, 2],
        "no-underscore-dangle": [2, { "allow": ["_id"] }]
    }

**Comment by tammychau99** [comment]
Waiting until end of sprint to merge to avoid multiple merge conflicts

**Comment by jenisa10** [comment]
+2 hours for frontend and fixing code styling
